# Generated by Django 2.2.8 on 2020-06-26 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kozer', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
    ]
